name: app_api
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dio: ^5.4.0
  sqflite: ^2.2.6
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.14
  path: ^1.8.2
  image_picker: ^0.8.4+4
  intl: ^0.19.0
  file_picker: ^5.5.0
  provider: ^6.0.5
  http: ^0.13.5
  badges: ^2.0.1
  url_launcher: ^6.1.10
  google_nav_bar: ^5.0.6
  curved_navigation_bar: ^1.0.1
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  animated_notch_bottom_bar: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Bold.ttf
        weight: 700
